### PR TITLE
Add ElemRV from May 2024 tape-out

### PR DESCRIPTION
**Pull request by dnltz**
25 MHz MCU with a 5 stage RISC-V CPU. Loads code from an external SPI NOR-Flash and uses a HyperBus interface for external HyperRAM. Has a UART IP for debug communication and 4 GPIO pins.

### CODE REVIEW

**Comment by mi-and-core** [comment]
Missing bondpad_70x70.lef / .gds ?

**Comment by dnltz** [comment]
> Missing bondpad_70x70.lef / .gds ?

No, those files are located here https://github.com/dnltz/OpenROAD-flow-scripts/commits/IHP-May24

**Comment by mi-and-core** [comment]
Thanks

**Comment by dnltz** [comment]
> Thanks

This is the environment we used to build: https://github.com/dnltz/ElemRV-init

**Pull request merged**
